### ISSUE TITLE
Use Git tags

### ISSUE THREAD

**Issue by ludovicc** [harbur/captain#19]
If I tag the code with something like RELEASE_1_0 in Git, it would be great to have a regex that detects it in captain and tags the container with version 1.0

**Comment by spiddy** [comment]
Currently the tags are supported, they are detected and the container is tagged, but with the same name.

The following two things are currently missing from what you propose:
- Regex to activate tagging (currently all git tags activate docker tagging, regex activation is on the [roadmap](https://github.com/harbur/captain#roadmap))
- Tag string conversion

This is discussable. I believe git+docker tags parity is essential for traceability reasons. I do find the same need just for one reason, there is currently no way to tell apart docker tags coming from git branches, or from git tags. But given the implementation of git, this shouldn't be a problem, since almost nobody will name a branch and a tag same name (otherwise 'git checkout name' will give you an ambiguity warning). In the future I believe docker labels will be able to be added on docker build to get metadata burned-in the image.

Is there another reason / use case for parsing and manipulating the string to something other that the git tag or is the current implementation sufficient?

**Comment by spiddy** [comment]
note: Current implementation only supports one tag per commit-id. That can be improved

**Comment by ludovicc** [comment]
The current implementation seems sufficient. Documentation should mention that tag-name is used.

**Comment by spiddy** [comment]
Documentation has been added here https://github.com/harbur/captain#docker-tags-lifecycle to reflect the reality.
